/* ==========================================================================
   Pickify Lab — Product Data
   Static product catalogue. In a future migration (see README), this file
   is replaced by a call to a real API / database — every other script reads
   from window.PICKIFY_PRODUCTS so that swap requires no UI changes.
   ========================================================================== */

const PICKIFY_PRODUCTS = [
  {
    id: 1,
    slug: "cerave-hydrating-facial-cleanser",
    name: "Hydrating Facial Cleanser",
    brand: "CeraVe",
    category: "Cleanser",
    skinType: ["Dry", "Normal", "Sensitive"],
    skinConcern: ["Dehydration", "Barrier repair"],
    keywords: ["ceramide", "gentle", "fragrance-free", "everyday cleanser"],
    rating: 4.7,
    reviewCount: 18342,
    matchScore: 96,
    badges: ["Best Seller", "Dermatologist Recommended"],
    price: "$",
    icon: "fa-droplet",
    shortReview: "A creamy, non-foaming cleanser that leaves skin soft without any tightness.",
    overview: "A fragrance-free, non-foaming cream cleanser built around three essential ceramides and hyaluronic acid, designed to lift away dirt and makeup while leaving the skin barrier undisturbed.",
    pros: ["Doesn't strip or tighten skin", "Fragrance-free formula", "Works well morning and night", "Affordable price per ounce", "Fits well into layered routines"],
    cons: ["Doesn't remove heavy waterproof makeup on its own", "Can feel too rich for very oily skin", "Tub packaging can be less hygienic than a pump"],
    review: "This is the cleanser I recommend most often to people rebuilding a damaged moisture barrier. It uses a milky, lotion-like texture rather than a foam, so it never leaves that squeaky-clean feeling that usually means your skin has been over-stripped. After a month of daily use in my own routine, redness and flaking around my nose noticeably calmed down.",
    ingredients: ["Ceramides 1, 3 & 6-II", "Hyaluronic Acid", "MVE Delivery Technology", "Glycerin"],
    howToUse: "Massage onto damp skin morning and night, then rinse with lukewarm water. No need to follow with a second cleanse unless wearing heavy sunscreen or makeup.",
    whoFor: "Anyone with dry, normal, or reactive skin who wants a wash that supports rather than fights the skin barrier.",
    whoAvoid: "Those with very oily or acne-congested skin may prefer a lighter gel cleanser.",
    faqs: [
      { q: "Is it safe for sensitive skin?", a: "Yes — it's fragrance-free and formulated with the National Eczema Association's approval in mind." },
      { q: "Will it remove sunscreen?", a: "It removes most everyday sunscreens, but mineral or waterproof formulas may need an oil cleanser first." }
    ],
    amazonLink: "#"
  },
  {
    id: 2,
    slug: "cerave-moisturizing-cream",
    name: "Moisturizing Cream",
    brand: "CeraVe",
    category: "Moisturizer",
    skinType: ["Dry", "Very Dry", "Normal"],
    skinConcern: ["Dehydration", "Barrier repair", "Rough texture"],
    keywords: ["ceramide", "thick", "night cream", "body and face"],
    rating: 4.8,
    reviewCount: 24110,
    matchScore: 97,
    badges: ["Best Seller", "Editor's Choice"],
    price: "$",
    icon: "fa-jar",
    shortReview: "A rich, tub-sized cream that keeps skin comfortable through the driest months.",
    overview: "A thick, fast-absorbing cream that combines three ceramides, hyaluronic acid, and MVE technology to deliver moisture in slow release throughout the day.",
    pros: ["Long-lasting hydration", "Large tub offers real value", "Non-greasy despite rich texture", "Suitable for face and body"],
    cons: ["Too heavy for oily or acne-prone skin in summer", "Contains no SPF, so a separate sunscreen is needed"],
    review: "I switch to this every winter when my skin starts flaking at the jaw. The MVE delivery system genuinely seems to slow-release moisture — my skin still feels comfortable twelve hours after applying, without a greasy film sitting on top.",
    ingredients: ["Ceramides 1, 3 & 6-II", "Hyaluronic Acid", "Petrolatum", "MVE Delivery Technology"],
    howToUse: "Apply a generous layer to face and body after cleansing, both morning and night.",
    whoFor: "Dry, very dry, or normal skin types, especially in cold or low-humidity climates.",
    whoAvoid: "Oily or breakout-prone skin, particularly in warm, humid weather.",
    faqs: [
      { q: "Can I use it on my body too?", a: "Yes, the tub size is intended for both face and body use." }
    ],
    amazonLink: "#"
  },
  {
    id: 3,
    slug: "cerave-foaming-facial-cleanser",
    name: "Foaming Facial Cleanser",
    brand: "CeraVe",
    category: "Cleanser",
    skinType: ["Oily", "Combination", "Normal"],
    skinConcern: ["Excess oil", "Congestion"],
    keywords: ["foam", "oily skin", "niacinamide", "gel wash"],
    rating: 4.6,
    reviewCount: 15230,
    matchScore: 93,
    badges: ["New Review"],
    price: "$",
    icon: "fa-droplet",
    shortReview: "A gentle foaming gel that controls shine without leaving skin tight.",
    overview: "A foaming gel cleanser with ceramides, niacinamide, and hyaluronic acid, formulated for normal to oily skin that still wants barrier support.",
    pros: ["Controls midday shine", "Doesn't leave a tight, dry finish", "Niacinamide helps calm redness"],
    cons: ["Foam can feel drying if over-used", "Not strong enough alone for heavy makeup removal"],
    review: "This has become my go-to morning cleanser. It foams up lightly rather than aggressively, so it clears overnight oil without the tight, dehydrated feeling that a lot of foaming cleansers leave behind.",
    ingredients: ["Ceramides 1, 3 & 6-II", "Niacinamide", "Hyaluronic Acid"],
    howToUse: "Work into a light lather on wet skin, massage for 30 seconds, then rinse thoroughly.",
    whoFor: "Normal, combination, and oily skin looking for oil control without stripping.",
    whoAvoid: "Very dry or highly reactive skin may find foaming formulas too drying.",
    faqs: [],
    amazonLink: "#"
  },
  {
    id: 4,
    slug: "eucerin-eye-repair-cream",
    name: "Advanced Repair Eye Cream",
    brand: "Eucerin",
    category: "Eye Cream",
    skinType: ["Dry", "Normal", "Mature"],
    skinConcern: ["Fine lines", "Dark circles", "Puffiness"],
    keywords: ["eye cream", "wrinkles", "under eye", "hydration"],
    rating: 4.4,
    reviewCount: 6120,
    matchScore: 88,
    badges: ["Dermatologist Recommended"],
    price: "$$",
    icon: "fa-eye",
    shortReview: "A lightweight eye cream that softens fine lines without irritating the eye area.",
    overview: "A fragrance-free eye cream with ceramides and licorice root extract, formulated specifically for the thin, sensitive skin around the eyes.",
    pros: ["Fragrance-free and ophthalmologist-tested", "Absorbs quickly with no white cast", "Noticeably softens crepiness over time"],
    cons: ["Minimal effect on deep-set dark circles", "Smaller tube relative to price"],
    review: "I was cautious trying a new eye cream given how reactive that skin can be, but this has caused zero irritation over three months of nightly use, and the fine lines at the outer corners look visibly softer.",
    ingredients: ["Ceramide NP", "Licorice Root Extract", "Glycerin"],
    howToUse: "Dot a small amount around the orbital bone morning and night, patting gently with the ring finger.",
    whoFor: "Anyone noticing early fine lines, dryness, or puffiness around the eyes.",
    whoAvoid: "Those seeking strong dark-circle brightening may need a targeted vitamin C or caffeine formula instead.",
    faqs: [
      { q: "Can it be used under makeup?", a: "Yes, it absorbs quickly enough to layer concealer on top within a minute or two." }
    ],
    amazonLink: "#"
  },
  {
    id: 5,
    slug: "laroche-posay-anthelios-melt-in-sunscreen",
    name: "Anthelios Melt-in Milk Sunscreen SPF 60",
    brand: "La Roche-Posay",
    category: "Sunscreen",
    skinType: ["All Skin Types"],
    skinConcern: ["Sun protection", "Uneven tone"],
    keywords: ["spf", "broad spectrum", "daily sunscreen", "sun cream"],
    rating: 4.6,
    reviewCount: 12890,
    matchScore: 95,
    badges: ["Best Seller"],
    price: "$$",
    icon: "fa-sun",
    shortReview: "A silky, fast-absorbing SPF 60 that layers invisibly under makeup.",
    overview: "A broad-spectrum SPF 60 milk sunscreen using a blend of chemical filters, formulated to sink in within minutes and leave no white cast on any skin tone.",
    pros: ["No white cast on deeper skin tones", "Absorbs fast, no pilling under makeup", "Water resistant up to 80 minutes"],
    cons: ["Chemical filters may not suit very reactive skin", "Bottle empties quickly with daily use"],
    review: "This is the sunscreen I hand to friends who say they 'hate how sunscreen feels.' It genuinely melts in within a minute, leaving a satin finish rather than the greasy or chalky look so many SPFs leave behind.",
    ingredients: ["Avobenzone", "Homosalate", "Octisalate", "Cell-Ox Shield Technology"],
    howToUse: "Apply generously as the last step of your morning routine, and reapply every two hours in direct sun.",
    whoFor: "Anyone wanting a daily, makeup-friendly broad-spectrum sunscreen.",
    whoAvoid: "Those with chemical-filter sensitivities may prefer a mineral formula instead.",
    faqs: [
      { q: "Does it leave a white cast?", a: "No — it's a chemical formula that dries clear on all skin tones." }
    ],
    amazonLink: "#"
  },
  {
    id: 6,
    slug: "laroche-posay-toleriane-double-repair",
    name: "Toleriane Double Repair Moisturizer",
    brand: "La Roche-Posay",
    category: "Moisturizer",
    skinType: ["Normal", "Combination", "Sensitive"],
    skinConcern: ["Barrier repair", "Dehydration"],
    keywords: ["ceramide", "niacinamide", "gel-cream", "daily moisturizer"],
    rating: 4.6,
    reviewCount: 9871,
    matchScore: 94,
    badges: ["Dermatologist Recommended"],
    price: "$$",
    icon: "fa-jar",
    shortReview: "A featherlight gel-cream that hydrates without any greasy residue.",
    overview: "A dual-action moisturizer with ceramides, niacinamide, and prebiotic thermal water, built to repair the skin barrier while controlling shine.",
    pros: ["Lightweight, non-greasy finish", "Layers well under sunscreen and makeup", "Calms redness over consistent use"],
    cons: ["Not rich enough for very dry winter skin", "Contains fragrance-adjacent stabilizers some sensitive users notice"],
    review: "As someone with combination skin, this is the rare moisturizer that hydrates my cheeks without making my T-zone shinier by noon. It sits under sunscreen with zero pilling.",
    ingredients: ["Ceramide-3", "Niacinamide", "Prebiotic Thermal Water", "Glycerin"],
    howToUse: "Apply to clean skin morning and night as the final hydrating step before sunscreen or makeup.",
    whoFor: "Normal, combination, or sensitive skin wanting light daily hydration.",
    whoAvoid: "Very dry skin types may need a richer cream, especially in winter.",
    faqs: [],
    amazonLink: "#"
  },
  {
    id: 7,
    slug: "laroche-posay-effaclar-duo",
    name: "Effaclar Duo+ Dual Action Acne Treatment",
    brand: "La Roche-Posay",
    category: "Acne Treatment",
    skinType: ["Oily", "Acne-Prone", "Combination"],
    skinConcern: ["Breakouts", "Blackheads", "Post-acne marks"],
    keywords: ["benzoyl peroxide alternative", "salicylic acid", "acne cream", "blemish"],
    rating: 4.3,
    reviewCount: 11234,
    matchScore: 89,
    badges: ["Trending"],
    price: "$$",
    icon: "fa-hand-sparkles",
    shortReview: "A leave-on gel that targets blackheads and breakouts without over-drying skin.",
    overview: "A dual-action treatment combining salicylic and lipo-hydroxy acid to unclog pores, paired with niacinamide to reduce the appearance of post-acne marks.",
    pros: ["Visible reduction in blackheads within weeks", "Doesn't over-dry like some spot treatments", "Fragrance-free"],
    cons: ["Slow to show results on deeper cystic acne", "Mild tingling on first few uses"],
    review: "I've used this as an all-over thin layer rather than a spot treatment, and after six weeks my pores around the nose look noticeably smaller and clearer.",
    ingredients: ["Salicylic Acid", "Lipo-Hydroxy Acid", "Niacinamide", "Micro-Exfoliating Perlite"],
    howToUse: "Apply a thin layer over acne-prone areas once or twice daily after cleansing.",
    whoFor: "Oily and acne-prone skin dealing with blackheads and mild to moderate breakouts.",
    whoAvoid: "Very dry or sensitive skin, or those with cystic acne needing a dermatologist-prescribed treatment.",
    faqs: [
      { q: "Can it be used with retinol?", a: "Alternate nights with retinol is recommended to avoid over-exfoliating the skin barrier." }
    ],
    amazonLink: "#"
  },
  {
    id: 8,
    slug: "cosrx-snail-mucin-essence",
    name: "Advanced Snail 96 Mucin Power Essence",
    brand: "COSRX",
    category: "Serum",
    skinType: ["All Skin Types", "Sensitive"],
    skinConcern: ["Dehydration", "Dullness", "Redness"],
    keywords: ["snail mucin", "k-beauty", "hydrating essence", "glass skin"],
    rating: 4.7,
    reviewCount: 21980,
    matchScore: 97,
    badges: ["Trending", "Best Seller"],
    price: "$",
    icon: "fa-flask",
    shortReview: "A sticky-to-dewy essence that repairs and plumps skin overnight.",
    overview: "A 96% snail secretion filtrate essence that supports hydration, elasticity, and visible repair, widely credited as a gateway product into K-beauty routines.",
    pros: ["Noticeable overnight glow", "Layers well under other serums", "Large bottle for the price"],
    cons: ["Tacky texture takes a minute to absorb", "Snail mucin origin isn't for everyone"],
    review: "It sounds unusual, but this is the product that finally calmed the redness and tightness I used to get every winter. It's tacky for the first minute, then sinks in to leave skin genuinely dewy by morning.",
    ingredients: ["Snail Secretion Filtrate (96%)", "Betaine", "Sodium Hyaluronate"],
    howToUse: "Pat two to three drops onto clean skin after toner, before moisturizer, morning and night.",
    whoFor: "Anyone wanting extra hydration and a dewy finish, including sensitive skin.",
    whoAvoid: "Those who dislike tacky textures may prefer a lighter, faster-absorbing serum.",
    faqs: [],
    amazonLink: "#"
  },
  {
    id: 9,
    slug: "cosrx-salicylic-acid-cleanser",
    name: "Salicylic Acid Daily Gentle Cleanser",
    brand: "COSRX",
    category: "Cleanser",
    skinType: ["Oily", "Acne-Prone", "Combination"],
    skinConcern: ["Breakouts", "Excess oil", "Enlarged pores"],
    keywords: ["bha cleanser", "acne wash", "gentle exfoliating cleanser"],
    rating: 4.5,
    reviewCount: 8760,
    matchScore: 91,
    badges: ["Budget Pick"],
    price: "$",
    icon: "fa-droplet",
    shortReview: "A low-pH gel cleanser that gently decongests pores every day.",
    overview: "A low-pH cleanser with betaine salicylate, formulated to exfoliate pores gently enough for daily use without the harshness of traditional BHA acids.",
    pros: ["Low-pH formula respects the skin barrier", "Visible pore decongestion over time", "Affordable everyday price"],
    cons: ["Not strong enough as a sole acne treatment", "Foam is minimal, which some find less satisfying"],
    review: "This has replaced my old foaming cleanser entirely. It's gentle enough for daily use but I can genuinely see fewer clogged pores across my nose after a month.",
    ingredients: ["Betaine Salicylate", "Tea Tree Leaf Water", "Panthenol"],
    howToUse: "Massage onto damp skin, focusing on oily zones, then rinse thoroughly.",
    whoFor: "Oily and acne-prone skin wanting daily gentle exfoliation.",
    whoAvoid: "Dry or sensitive skin types may find daily use too much.",
    faqs: [],
    amazonLink: "#"
  },
  {
    id: 10,
    slug: "cosrx-aha-bha-toner",
    name: "AHA/BHA Clarifying Treatment Toner",
    brand: "COSRX",
    category: "Toner",
    skinType: ["Oily", "Combination", "Acne-Prone"],
    skinConcern: ["Texture", "Breakouts", "Dullness"],
    keywords: ["exfoliating toner", "aha bha", "clarifying toner"],
    rating: 4.4,
    reviewCount: 7320,
    matchScore: 90,
    badges: [],
    price: "$",
    icon: "fa-bottle-droplet",
    shortReview: "A leave-on exfoliating toner that smooths texture without the sting.",
    overview: "A gentle exfoliating toner combining glycolic acid, betaine salicylate, and calming botanicals to refine texture and clarity over time.",
    pros: ["Visible texture improvement within a few weeks", "Calming botanicals reduce irritation", "Multi-use as toner or exfoliating mask"],
    cons: ["Requires patch testing for sensitive skin", "Not suitable for daily use for beginners"],
    review: "Used two to three times a week, this has smoothed out the rough texture I used to get on my forehead, without the redness I've experienced from stronger exfoliants.",
    ingredients: ["Glycolic Acid", "Betaine Salicylate", "Centella Asiatica Extract"],
    howToUse: "Sweep across clean skin with a cotton pad two to three times weekly, building up tolerance gradually.",
    whoFor: "Oily and combination skin wanting gentle chemical exfoliation.",
    whoAvoid: "Sensitive, compromised, or actively irritated skin.",
    faqs: [
      { q: "Can I use it every day?", a: "Start two to three times weekly and increase only if your skin tolerates it well." }
    ],
    amazonLink: "#"
  },
  {
    id: 11,
    slug: "ordinary-niacinamide-zinc",
    name: "Niacinamide 10% + Zinc 1%",
    brand: "The Ordinary",
    category: "Serum",
    skinType: ["Oily", "Combination", "Acne-Prone"],
    skinConcern: ["Excess oil", "Enlarged pores", "Blemishes"],
    keywords: ["niacinamide serum", "oil control", "pore minimizer"],
    rating: 4.3,
    reviewCount: 34200,
    matchScore: 92,
    badges: ["Best Seller", "Budget Pick"],
    price: "$",
    icon: "fa-flask",
    shortReview: "A cult-favorite serum that visibly tightens pores and controls oil.",
    overview: "A high-strength niacinamide and zinc serum designed to regulate sebum production and visibly reduce the appearance of blemishes and enlarged pores.",
    pros: ["Extremely affordable per use", "Visible oil control within weeks", "Fits into almost any routine"],
    cons: ["Can pill under heavier products if over-applied", "High concentration may irritate very sensitive skin"],
    review: "For the price, nothing else in my routine has made as visible a difference to oiliness by midday. A few drops in the morning and I no longer need to blot by early afternoon.",
    ingredients: ["Niacinamide (10%)", "Zinc PCA (1%)"],
    howToUse: "Apply a few drops to clean skin morning and/or night before heavier creams.",
    whoFor: "Oily and acne-prone skin looking to control shine and refine pores.",
    whoAvoid: "Very sensitive skin, or those already using multiple active ingredients.",
    faqs: [
      { q: "Does it help with acne scars?", a: "It can help fade the appearance of post-acne marks over consistent, long-term use, though it isn't a treatment for active acne." }
    ],
    amazonLink: "#"
  },
  {
    id: 12,
    slug: "ordinary-hyaluronic-acid",
    name: "Hyaluronic Acid 2% + B5",
    brand: "The Ordinary",
    category: "Serum",
    skinType: ["All Skin Types", "Dry"],
    skinConcern: ["Dehydration", "Plumpness"],
    keywords: ["hyaluronic acid serum", "hydrating serum", "plumping"],
    rating: 4.4,
    reviewCount: 41200,
    matchScore: 93,
    badges: ["Best Seller"],
    price: "$",
    icon: "fa-flask",
    shortReview: "A lightweight, multi-molecular-weight hydrator that plumps skin instantly.",
    overview: "A hydrating serum using multiple molecular weights of hyaluronic acid alongside vitamin B5, designed to draw and hold moisture at different layers of the skin.",
    pros: ["Immediate plumping effect", "Layers under any moisturizer", "Very affordable"],
    cons: ["Must be applied to damp skin, or it can feel dehydrating in dry climates", "Bottle dropper can dispense too much at once"],
    review: "The trick I learned the hard way: apply this only to slightly damp skin, then seal with moisturizer. Done that way, it's genuinely plumping; done on bone-dry skin, it can backfire.",
    ingredients: ["Hyaluronic Acid (multiple molecular weights)", "Panthenol (Vitamin B5)"],
    howToUse: "Apply to damp skin after cleansing, then follow immediately with a moisturizer to lock in hydration.",
    whoFor: "Any skin type wanting an extra layer of lightweight hydration.",
    whoAvoid: "Those in very dry climates should always pair it with a moisturizer, never use it alone.",
    faqs: [],
    amazonLink: "#"
  },
  {
    id: 13,
    slug: "ordinary-squalane-cleanser",
    name: "Squalane Cleanser",
    brand: "The Ordinary",
    category: "Cleanser",
    skinType: ["Dry", "Sensitive", "Normal"],
    skinConcern: ["Dehydration", "Makeup removal"],
    keywords: ["oil cleanser", "squalane", "makeup remover", "gentle cleanser"],
    rating: 4.2,
    reviewCount: 9430,
    matchScore: 87,
    badges: [],
    price: "$",
    icon: "fa-droplet",
    shortReview: "A silky oil cleanser that melts away makeup without a greasy after-feel.",
    overview: "A lightweight, silicone-free oil cleanser built around plant-derived squalane, designed to dissolve makeup and sunscreen without disrupting the skin barrier.",
    pros: ["Removes makeup and sunscreen effectively", "Doesn't clog pores despite oil base", "Rinses cleanly with water"],
    cons: ["Needs a second cleanse for a fully clean feel", "Pump can be finicky when bottle is nearly empty"],
    review: "As a first-cleanse step, this takes off a full face of makeup and SPF in under a minute, and rinses away completely clean rather than leaving a film.",
    ingredients: ["Squalane", "Vitamin E", "Polysorbate 60"],
    howToUse: "Massage onto dry skin to dissolve makeup and sunscreen, then rinse or follow with a water-based cleanser.",
    whoFor: "Anyone wearing makeup or sunscreen who wants a gentle first-cleanse step.",
    whoAvoid: "Those who prefer a single-step wash may find a two-step routine unnecessary.",
    faqs: [],
    amazonLink: "#"
  },
  {
    id: 14,
    slug: "cetaphil-gentle-skin-cleanser",
    name: "Gentle Skin Cleanser",
    brand: "Cetaphil",
    category: "Cleanser",
    skinType: ["Sensitive", "Dry", "Normal"],
    skinConcern: ["Irritation", "Dehydration"],
    keywords: ["gentle cleanser", "soap-free", "sensitive skin wash"],
    rating: 4.6,
    reviewCount: 27650,
    matchScore: 94,
    badges: ["Dermatologist Recommended", "Best Seller"],
    price: "$",
    icon: "fa-droplet",
    shortReview: "The classic no-rinse-required cleanser dermatologists have trusted for decades.",
    overview: "A soap-free, fragrance-free cleanser that has been a dermatology staple for decades, gentle enough to use with or without water.",
    pros: ["Extremely gentle, rarely causes reactions", "Can be used without rinsing in a pinch", "Widely available and affordable"],
    cons: ["Doesn't feel deeply cleansing for oily skin", "Minimal foam or lather"],
    review: "This is the cleanser my dermatologist recommended after a bad reaction to a trendy acid wash, and months later it's still the only thing that's never once irritated my skin.",
    ingredients: ["Cetyl Alcohol", "Propylene Glycol", "Sodium Lauryl Sulfate (trace)"],
    howToUse: "Massage onto skin and rinse, or wipe away with a soft cloth if water isn't available.",
    whoFor: "Sensitive, dry, or reactive skin wanting a fuss-free daily wash.",
    whoAvoid: "Oily skin types wanting a deeper, foaming clean.",
    faqs: [],
    amazonLink: "#"
  },
  {
    id: 15,
    slug: "cetaphil-moisturizing-cream",
    name: "Moisturizing Cream",
    brand: "Cetaphil",
    category: "Moisturizer",
    skinType: ["Dry", "Very Dry", "Sensitive"],
    skinConcern: ["Dehydration", "Eczema-prone skin"],
    keywords: ["thick moisturizer", "sensitive skin cream", "fragrance free"],
    rating: 4.7,
    reviewCount: 19870,
    matchScore: 95,
    badges: ["Best Seller"],
    price: "$",
    icon: "fa-jar",
    shortReview: "A dense, protective cream built for the driest, most reactive skin.",
    overview: "A rich, fragrance-free moisturizer designed for very dry and sensitive skin, using glycerin and a protective occlusive base to lock in moisture for hours.",
    pros: ["Very long-lasting hydration", "Fragrance-free and dye-free", "Large jar offers strong value"],
    cons: ["Heavy texture unsuitable for oily skin", "Takes a moment to fully absorb"],
    review: "During a particularly harsh winter this was the only moisturizer that stopped the cracking on my knuckles and cheeks, and it's stayed in my routine ever since for cold-weather months.",
    ingredients: ["Glycerin", "Panthenol", "Macadamia Seed Oil"],
    howToUse: "Apply liberally to face and body as needed, especially after bathing.",
    whoFor: "Very dry, sensitive, or eczema-prone skin.",
    whoAvoid: "Oily or acne-prone skin, especially in warmer climates.",
    faqs: [],
    amazonLink: "#"
  },
  {
    id: 16,
    slug: "neutrogena-ultra-sheer-sunscreen",
    name: "Ultra Sheer Dry-Touch Sunscreen SPF 100",
    brand: "Neutrogena",
    category: "Sunscreen",
    skinType: ["All Skin Types", "Oily"],
    skinConcern: ["Sun protection"],
    keywords: ["high spf", "dry touch sunscreen", "sport sunscreen"],
    rating: 4.6,
    reviewCount: 22140,
    matchScore: 94,
    badges: ["Best Seller"],
    price: "$",
    icon: "fa-sun",
    shortReview: "A high-SPF formula with a genuinely dry, matte finish.",
    overview: "A broad-spectrum SPF 100 sunscreen engineered with a dry-touch technology that absorbs excess oil for a matte finish, popular for sport and daily wear alike.",
    pros: ["Very high SPF protection", "Genuinely matte, non-greasy finish", "Water resistant up to 80 minutes"],
    cons: ["Contains alcohol, which may dry out sensitive skin", "Can leave a slight sheen in humid weather"],
    review: "I keep a bottle of this in my gym bag. It's the rare high-SPF sunscreen that doesn't leave a greasy sheen, which makes it easy to reapply without ruining makeup.",
    ingredients: ["Avobenzone", "Homosalate", "Octisalate", "Octocrylene"],
    howToUse: "Apply 15 minutes before sun exposure and reapply every two hours or after swimming or sweating.",
    whoFor: "Oily skin or anyone wanting maximum SPF with a matte finish.",
    whoAvoid: "Dry or alcohol-sensitive skin may find it drying with frequent reapplication.",
    faqs: [],
    amazonLink: "#"
  },
  {
    id: 17,
    slug: "neutrogena-hydro-boost-water-gel",
    name: "Hydro Boost Water Gel",
    brand: "Neutrogena",
    category: "Moisturizer",
    skinType: ["Oily", "Combination", "Normal"],
    skinConcern: ["Dehydration", "Dullness"],
    keywords: ["water gel", "hyaluronic acid moisturizer", "lightweight moisturizer"],
    rating: 4.6,
    reviewCount: 31200,
    matchScore: 93,
    badges: ["Trending", "Best Seller"],
    price: "$",
    icon: "fa-jar",
    shortReview: "A bouncy, water-based gel that hydrates oily skin without added shine.",
    overview: "A gel-cream moisturizer built on a hyaluronic acid base, designed to hydrate deeply while staying lightweight enough for oily and combination skin.",
    pros: ["Absorbs quickly with no greasy residue", "Great under makeup", "Noticeably plumping texture"],
    cons: ["Some added fragrance may bother sensitive users", "Not rich enough for very dry skin in winter"],
    review: "This completely changed how I feel about moisturizer as someone with oily skin who used to skip it. It hydrates without adding any extra shine, and my makeup applies more smoothly over it.",
    ingredients: ["Hyaluronic Acid", "Glycerin", "Dimethicone"],
    howToUse: "Apply to clean skin morning and night, pressing gently into the skin for best absorption.",
    whoFor: "Oily, combination, or normal skin wanting lightweight hydration.",
    whoAvoid: "Very dry skin types in cold climates may need a richer cream.",
    faqs: [],
    amazonLink: "#"
  },
  {
    id: 18,
    slug: "beauty-of-joseon-relief-sun",
    name: "Relief Sun: Rice + Probiotics SPF50",
    brand: "Beauty of Joseon",
    category: "Sunscreen",
    skinType: ["All Skin Types", "Sensitive"],
    skinConcern: ["Sun protection", "Dullness"],
    keywords: ["k-beauty sunscreen", "rice sunscreen", "no white cast"],
    rating: 4.7,
    reviewCount: 16540,
    matchScore: 96,
    badges: ["Trending", "New Review"],
    price: "$",
    icon: "fa-sun",
    shortReview: "A weightless K-beauty sunscreen with a natural, skin-like finish.",
    overview: "A chemical sunscreen infused with rice extract and probiotics, formulated to leave a dewy, natural finish rather than a matte or chalky one.",
    pros: ["No white cast whatsoever", "Feels like skincare, not sunscreen", "Doubles nicely as a makeup primer"],
    cons: ["Limited water resistance compared to sport formulas", "Not widely available in physical stores"],
    review: "This has become the sunscreen I recommend to friends who 'don't like how sunscreen feels' — it genuinely sits like a light serum, and I've started using it under makeup daily.",
    ingredients: ["Rice Extract", "Niacinamide", "Butylene Glycol"],
    howToUse: "Apply as the last step of your morning skincare routine, reapplying every two hours in direct sun.",
    whoFor: "Anyone wanting a natural-finish, comfortable daily sunscreen.",
    whoAvoid: "Those needing high water resistance for swimming or heavy sweating.",
    faqs: [],
    amazonLink: "#"
  },
  {
    id: 19,
    slug: "beauty-of-joseon-glow-serum",
    name: "Glow Serum: Propolis + Niacinamide",
    brand: "Beauty of Joseon",
    category: "Serum",
    skinType: ["All Skin Types", "Dull"],
    skinConcern: ["Dullness", "Uneven tone"],
    keywords: ["glow serum", "propolis", "niacinamide serum", "brightening"],
    rating: 4.6,
    reviewCount: 13870,
    matchScore: 95,
    badges: ["Trending"],
    price: "$",
    icon: "fa-flask",
    shortReview: "A silky serum that leaves skin visibly brighter within days.",
    overview: "A brightening serum combining propolis extract and niacinamide, designed to even tone and add a healthy radiance without a sticky finish.",
    pros: ["Visible glow within a few days", "Absorbs quickly, no tackiness", "Pleasant, subtle honey-like scent"],
    cons: ["Contains fragrance, which may not suit very sensitive skin", "Small bottle relative to how quickly it's used"],
    review: "Within about a week of nightly use, coworkers started asking if I'd changed my skincare — it gives a genuine, healthy glow rather than a temporary dewy filter effect.",
    ingredients: ["Propolis Extract (60%)", "Niacinamide", "Panthenol"],
    howToUse: "Apply two to three drops to clean skin after toner, morning or night, before moisturizer.",
    whoFor: "Anyone wanting brighter, more even-toned skin.",
    whoAvoid: "Fragrance-sensitive skin should patch test first.",
    faqs: [],
    amazonLink: "#"
  },
  {
    id: 20,
    slug: "vanicream-gentle-facial-cleanser",
    name: "Gentle Facial Cleanser",
    brand: "Vanicream",
    category: "Cleanser",
    skinType: ["Sensitive", "Eczema-Prone", "Dry"],
    skinConcern: ["Irritation", "Dehydration"],
    keywords: ["free of dyes", "fragrance free cleanser", "sensitive skin cleanser"],
    rating: 4.5,
    reviewCount: 5210,
    matchScore: 90,
    badges: ["Dermatologist Recommended"],
    price: "$",
    icon: "fa-droplet",
    shortReview: "A minimalist cleanser built for the most reactive skin types.",
    overview: "A cleanser formulated without dyes, fragrance, parabens, or common irritants, designed for the most sensitive and reactive skin types, including eczema-prone skin.",
    pros: ["Free of common irritants", "Rarely triggers reactions", "Trusted by dermatologists for eczema"],
    cons: ["Minimal lather", "Packaging feels basic compared to premium brands"],
    review: "After years of reacting to 'sensitive skin' products that still contained fragrance, this was the first cleanser that caused zero flare-ups on my eczema-prone cheeks.",
    ingredients: ["Cetyl Alcohol", "Sodium Lauroyl Isethionate", "Glycerin"],
    howToUse: "Apply to wet skin, massage gently, and rinse thoroughly with lukewarm water.",
    whoFor: "Highly sensitive, allergy-prone, or eczema-prone skin.",
    whoAvoid: "Those wanting a foamier, more 'spa-like' cleansing experience.",
    faqs: [],
    amazonLink: "#"
  },
  {
    id: 21,
    slug: "vanicream-moisturizing-cream",
    name: "Moisturizing Cream",
    brand: "Vanicream",
    category: "Moisturizer",
    skinType: ["Sensitive", "Very Dry", "Eczema-Prone"],
    skinConcern: ["Dehydration", "Irritation"],
    keywords: ["fragrance free moisturizer", "sensitive skin cream", "eczema cream"],
    rating: 4.6,
    reviewCount: 6890,
    matchScore: 92,
    badges: [],
    price: "$",
    icon: "fa-jar",
    shortReview: "A jar of unscented, dye-free relief for very reactive skin.",
    overview: "A thick, unscented moisturizer free from common irritants, formulated for individuals with highly sensitive or eczema-prone skin who react to most fragranced products.",
    pros: ["Free of dyes, fragrance, and lanolin", "Long-lasting hydration", "Suitable for the whole family"],
    cons: ["Basic jar packaging", "Thick texture takes time to absorb"],
    review: "Our dermatologist recommended this for my son's eczema patches, and it's now the only moisturizer that keeps his skin calm through winter without any stinging on application.",
    ingredients: ["Sorbitol", "Sunflower Seed Oil", "Glycerin"],
    howToUse: "Apply liberally to affected areas as often as needed, especially after bathing.",
    whoFor: "Highly sensitive, allergy-prone, or eczema-prone skin of all ages.",
    whoAvoid: "Oily skin types wanting a lighter, faster-absorbing formula.",
    faqs: [],
    amazonLink: "#"
  },
  {
    id: 22,
    slug: "paulas-choice-2pct-bha",
    name: "Skin Perfecting 2% BHA Liquid Exfoliant",
    brand: "Paula's Choice",
    category: "Acne Treatment",
    skinType: ["Oily", "Combination", "Acne-Prone"],
    skinConcern: ["Blackheads", "Texture", "Enlarged pores"],
    keywords: ["bha exfoliant", "salicylic acid", "pore clearing", "cult favorite"],
    rating: 4.6,
    reviewCount: 28760,
    matchScore: 96,
    badges: ["Trending", "Best Seller"],
    price: "$$",
    icon: "fa-hand-sparkles",
    shortReview: "A leave-on liquid exfoliant with a devoted following for a reason.",
    overview: "A leave-on 2% salicylic acid exfoliant that penetrates deep into pores to clear congestion, smooth texture, and reduce the look of fine lines over time.",
    pros: ["Visible pore-clearing within a few weeks", "Smooths rough, bumpy texture", "Doesn't over-dry skin like harsher acids"],
    cons: ["Requires sunscreen due to increased sun sensitivity", "Some tingling on first applications"],
    review: "Genuinely lives up to the hype. My forehead texture, which used to look bumpy under makeup, is noticeably smoother after about six weeks of nightly use.",
    ingredients: ["Salicylic Acid (2%)", "Green Tea Extract", "Methylpropanediol"],
    howToUse: "Apply with a cotton pad or fingertips to clean skin, starting a few nights a week and building up tolerance.",
    whoFor: "Oily, combination, or acne-prone skin dealing with blackheads and texture.",
    whoAvoid: "Very dry or sun-sensitive skin should introduce it slowly and always wear SPF.",
    faqs: [
      { q: "Can I use it every night right away?", a: "No — start two to three times a week and build up gradually to avoid irritation." }
    ],
    amazonLink: "#"
  },
  {
    id: 23,
    slug: "paulas-choice-clay-mask",
    name: "Skin Perfecting Clay Mask",
    brand: "Paula's Choice",
    category: "Face Mask",
    skinType: ["Oily", "Combination"],
    skinConcern: ["Excess oil", "Enlarged pores", "Congestion"],
    keywords: ["clay mask", "pore mask", "oil control mask"],
    rating: 4.4,
    reviewCount: 7430,
    matchScore: 89,
    badges: [],
    price: "$$",
    icon: "fa-mask-face",
    shortReview: "A weekly clay mask that visibly tightens pores without over-drying.",
    overview: "A gentle clay mask that absorbs excess oil and draws out impurities from congested pores, formulated to avoid the tight, uncomfortable finish of harsher clay masks.",
    pros: ["Visible pore-tightening effect", "Doesn't leave skin uncomfortably tight", "A little goes a long way"],
    cons: ["Can dry out sensitive areas if left on too long", "Not a substitute for daily oil control"],
    review: "Used once a week, this leaves my T-zone noticeably less congested by the next morning, without the uncomfortable tightness I've felt from other clay masks.",
    ingredients: ["Kaolin Clay", "Sea Whip Extract", "Niacinamide"],
    howToUse: "Apply an even layer to clean skin, leave for 10 minutes, then rinse with lukewarm water.",
    whoFor: "Oily and combination skin wanting a weekly deep-clean.",
    whoAvoid: "Dry or sensitive skin should limit use or skip entirely.",
    faqs: [],
    amazonLink: "#"
  },
  {
    id: 24,
    slug: "bioderma-sensibio-micellar-water",
    name: "Sensibio H2O Micellar Water",
    brand: "Bioderma",
    category: "Toner",
    skinType: ["Sensitive", "All Skin Types"],
    skinConcern: ["Irritation", "Makeup removal"],
    keywords: ["micellar water", "makeup remover", "no-rinse cleanser"],
    rating: 4.7,
    reviewCount: 33410,
    matchScore: 95,
    badges: ["Best Seller", "Editor's Choice"],
    price: "$",
    icon: "fa-bottle-droplet",
    shortReview: "The iconic no-rinse micellar water that started the whole category.",
    overview: "A pH-balanced micellar water that lifts away makeup, sunscreen, and daily grime without rinsing, using micelle technology to attract impurities without disrupting the skin barrier.",
    pros: ["No rinsing required, ideal for travel", "Extremely gentle, even on eyes", "Doesn't leave a sticky residue"],
    cons: ["Not effective on waterproof mascara alone", "Large bottle can feel bulky to travel with"],
    review: "I keep a bottle by my bed for nights I'm too tired for a full routine — a few soaked cotton pads and my face is clean without a single drop of stinging near my eyes.",
    ingredients: ["Micellar Technology", "Cucumber Extract", "Mannitol"],
    howToUse: "Soak a cotton pad and sweep gently across the face and eyes; no rinsing needed.",
    whoFor: "Sensitive skin, contact lens wearers, and anyone wanting a fast no-rinse cleanse.",
    whoAvoid: "Those wearing heavy waterproof makeup may need a dedicated remover first.",
    faqs: [],
    amazonLink: "#"
  },
  {
    id: 25,
    slug: "aveeno-calm-restore-oat-gel",
    name: "Calm + Restore Oat Gel Moisturizer",
    brand: "Aveeno",
    category: "Moisturizer",
    skinType: ["Sensitive", "Normal", "Combination"],
    skinConcern: ["Redness", "Irritation", "Dehydration"],
    keywords: ["oat moisturizer", "calming gel", "redness relief"],
    rating: 4.5,
    reviewCount: 10230,
    matchScore: 91,
    badges: ["New Review"],
    price: "$",
    icon: "fa-jar",
    shortReview: "A soothing oat-based gel that calms redness while it hydrates.",
    overview: "A lightweight gel moisturizer built around feverfew and prebiotic oat, formulated to calm visible redness and reactivity while delivering all-day hydration.",
    pros: ["Visibly reduces redness over time", "Lightweight gel texture", "Fragrance-free"],
    cons: ["Less effective for very dry skin in winter", "Jar packaging less hygienic than a pump"],
    review: "My cheeks flush easily with weather changes, and after a few weeks of using this daily the redness looks noticeably calmer, even before makeup.",
    ingredients: ["Feverfew", "Prebiotic Oat", "Glycerin"],
    howToUse: "Apply to clean skin morning and night, gently pressing in rather than rubbing.",
    whoFor: "Sensitive or reactive skin dealing with redness and irritation.",
    whoAvoid: "Very dry skin in cold climates may need a richer cream on top.",
    faqs: [],
    amazonLink: "#"
  }
];

// Category metadata: icon + short description, used across categories page and nav
const PICKIFY_CATEGORIES = [
  { name: "Cleanser", icon: "fa-droplet", description: "The first step — lifting away the day without stripping your barrier." },
  { name: "Moisturizer", icon: "fa-jar", description: "Locking in hydration and keeping the barrier comfortable." },
  { name: "Serum", icon: "fa-flask", description: "Concentrated actives for texture, tone, and hydration." },
  { name: "Sunscreen", icon: "fa-sun", description: "Daily protection — the single most important step." },
  { name: "Toner", icon: "fa-bottle-droplet", description: "Prepping and balancing skin before the rest of your routine." },
  { name: "Face Mask", icon: "fa-mask-face", description: "Weekly resets for congestion, dullness, and texture." },
  { name: "Eye Cream", icon: "fa-eye", description: "Targeted care for the thinnest, most delicate skin on your face." },
  { name: "Acne Treatment", icon: "fa-hand-sparkles", description: "Focused formulas for breakouts, blackheads, and marks." }
];

if (typeof window !== "undefined") {
  window.PICKIFY_PRODUCTS = PICKIFY_PRODUCTS;
  window.PICKIFY_CATEGORIES = PICKIFY_CATEGORIES;
}
